#!/bin/bash

PARSED_INPUT_FILE="${1:-/dev/stdin}"
LF_FILE_NAME="${2:-/dev/stdout}"

ES_PIPELINE_DIR=$METAPHOR_DIR/pipelines/Spanish

< $PARSED_INPUT_FILE $ES_PIPELINE_DIR/LFGen/malt_to_prop.py > $LF_FILE_NAME
