#!/bin/bash

# Parse Spanish

TAGGED_INPUT_FILE="${1:-/dev/stdin}"
PARSED_FILE_NAME="${2:-/dev/stdout}"

MALT_PARSER_DIR=$METAPHOR_DIR/external-tools/maltparser-1.7.2

cat $TAGGED_INPUT_FILE | \
java -cp $MALT_PARSER_DIR/maltparser-1.7.2.jar:$MALT_PARSER_DIR \
     MaltParserWrap -c ancora_under40 -m parse -w $MALT_PARSER_DIR \
     -lfi parser.log > $PARSED_FILE_NAME
