#!/bin/bash

inputFile="${1:-/dev/stdin}"
taggedFileName="${2:-/dev/stdout}"


farsiPipelineDir=$METAPHOR_DIR/pipelines/Farsi

taggerDir=$farsiPipelineDir/tokenizer/stanford-postagger

taggerModelFile=$farsiPipelineDir/tokenizer/farsi.tagger.model.treebank

#POS tag the input file
cd $taggerDir

java -mx2G  -classpath stanford-postagger.jar edu.stanford.nlp.tagger.maxent.MaxentTagger -prop farsiPropsFile.prop -model $taggerModelFile -textFile $inputFile  > $taggedFileName #2>/dev/null
