#!/bin/bash

INPUT_FILE="${1:-/dev/stdin}"
OUTPUT_FILE="${2:-/dev/stdout}"

FA_TOK_DIR=$METAPHOR_DIR/pipelines/Farsi/tokenizer

$FA_TOK_DIR/replaceSemiSpaceWithDashInInput.py \
    < $INPUT_FILE | $FA_TOK_DIR/utf8-tokenize.perl |
    $FA_TOK_DIR/convertTokenizerOutputForTagger.py >$OUTPUT_FILE
