#!/bin/bash

taggedInputFile="${1:-/dev/stdin}"
parsedFileName="${2:-/dev/stdout}"
parserDir=$METAPHOR_DIR/external-tools/malt-1.5
cd $parserDir
cat $taggedInputFile | java -cp dist/malt/malt.jar:$parserDir maltParserWrap
#java -cp dist/malt/malt.jar:$parserDir maltParserWrap
