#!/bin/sh

PLATFORM=$(uname -s | tr '[:upper:]' '[:lower:]')

BIN=$METAPHOR_DIR/external-tools/tree-tagger-3.2/$PLATFORM/bin
CMD=$METAPHOR_DIR/external-tools/tree-tagger-3.2/cmd
LIB=$METAPHOR_DIR/external-tools/tree-tagger-3.2/$PLATFORM/lib

GERMANTAGGER=${CMD}/tree-tagger-german-utf8
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-utf8.par
PARFILE2=${LIB}/german-chunker-utf8.par
FILTER=${CMD}/filter-chunker-output-german.perl

$GERMANTAGGER $* |
perl -nae 'if ($#F==0){print}else{print "$F[0]-$F[1]\n"}' |
$TAGGER $PARFILE2 -token -sgml -eps 0.00000001 -hyphen-heuristics -quiet |
$FILTER |
$TAGGER -quiet -token -lemma -sgml $PARFILE
