#!/bin/sh

PLATFORM=$(uname -s | tr '[:upper:]' '[:lower:]')

BIN=$METAPHOR_DIR/external-tools/tree-tagger-3.2/$PLATFORM/bin
CMD=$METAPHOR_DIR/external-tools/tree-tagger-3.2/cmd
LIB=$METAPHOR_DIR/external-tools/tree-tagger-3.2/$PLATFORM/lib

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/german-abbreviations-utf8
PARFILE=${LIB}/german-utf8.par
LEXFILE=${LIB}/german-lexicon-utf8.txt
FILTER=${CMD}/filter-german-tags

$TOKENIZER -a $ABBR_LIST $* |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE  | 
# error correction
$FILTER
