#!/bin/bash

inputFileName="${1:-/dev/stdin}"
outputFileName="${2:-/dev/stdout}"

farsiPipelineDir=$METAPHOR_DIR/pipelines/Farsi

parseToLFConverter=$farsiPipelineDir/LFGen/convertParseTreeToLF.py
farsiWordsDict=$farsiPipelineDir/LFGen/farsiWordsForLFCreation.txt

# convert the parse results to LF

python $parseToLFConverter $inputFileName $outputFileName $farsiWordsDict
