#!/bin/bash

inputFile="${1:-/dev/stdin}"
outputFileName="${2:-/dev/stdout}"

farsiPipelineDir=$METAPHOR_DIR/pipelines/Farsi

if [ -d "$2" ]; then
	$farsiPipelineDir/tokenizer/farsilemm.py \
        $farsiPipelineDir/tokenizer/lemmatizationDict.txt < $inputFile |
	tee $2/preproc_o.txt |
	$farsiPipelineDir/tokenizer/tokenize |
	tee $2/tokenizer_o.txt |
	$farsiPipelineDir/tokenizer/addDot.py |
	tee $2/dot_o.txt |
	$farsiPipelineDir/tokenizer/tag |
	tee $2/tagger_o.txt |
	$farsiPipelineDir/tokenizer/taggedFileToCONLL.py |
	tee $2/parser_o.txt
	#$farsiPipelineDir/createLF > /dev/stdout
else
	$farsiPipelineDir/tokenizer/farsilemm.py \
        $farsiPipelineDir/tokenizer/lemmatizationDict.txt < $inputFile |
	$farsiPipelineDir/tokenizer/tokenize |
	$farsiPipelineDir/tokenizer/addDot.py |
	$farsiPipelineDir/tokenizer/tag |
	$farsiPipelineDir/tokenizer/taggedFileToCONLL.py > $outputFileName
	#$farsiPipelineDir/createLF > $outputFileName
fi
