#!/bin/bash

# Usage:
#   ./LF_Pipeline <input> <output>
# or
#   ./LF_Pipeline <input>
# or
#   < <input> ./LF_Pipeline

INPUT_FILE="${1:-/dev/stdin}"
OUTPUT_FILE="${2:-/dev/stdout}"

FA_PIPELINE_DIR=$METAPHOR_DIR/pipelines/Farsi

if [ -d "$2" ]; then
    $FA_PIPELINE_DIR/pre-parser < $INPUT_FILE |
    tee $2/preparse_o.txt |
    $FA_PIPELINE_DIR/parse |
    tee $2/parser_o.txt |
    $FA_PIPELINE_DIR/createLF > /dev/stdout
else
    $FA_PIPELINE_DIR/pre-parser < $INPUT_FILE |
    $FA_PIPELINE_DIR/parse |
    $FA_PIPELINE_DIR/createLF > $OUTPUT_FILE
fi
