#!/bin/sh


BIN=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/bin
CMD=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/cmd
LIB=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup-greek.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/greek.par

$TOKENIZER $* |
# recognition of MWLs
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

