#!/bin/sh


BIN=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/bin
CMD=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/cmd
LIB=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
