#!/bin/sh


BIN=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/bin
CMD=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/cmd
LIB=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
