#!/bin/sh


BIN=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/bin
CMD=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/cmd
LIB=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/lib

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/tokenize.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english.par
LEXFILE=${LIB}/english-lexicon.txt

$TOKENIZER -e -a $ABBR_LIST $* |
# remove empty lines
grep -v '^$' |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE | 
perl -pe 's/\tV[BDHV]/\tVB/;s/IN\/that/\tIN/;'
