#!/bin/sh


BIN=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/bin
CMD=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/cmd
LIB=$METAPHOR_DIR/external-tools/tree-tagger-3.2/linux/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/estonian-abbreviations
PARFILE=${LIB}/estonian.par
MWLFILE=${LIB}/estonian-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

