#! /bin/bash

parsedInputFile="${1:-/dev/stdin}"
lfFileName="${2:-/dev/stdout}"

RU_PIPELINE_DIR=$METAPHOR_DIR/pipelines/Russian

cat $parsedInputFile | python $RU_PIPELINE_DIR/malt_ru.py > $lfFileName

