#! /bin/bash
PLATFORM=linux
TREE_TAGGER_BIN=$METAPHOR_DIR/external-tools/tree-tagger-3.2/$PLATFORM/bin
TREE_TAGGER_CMD=$METAPHOR_DIR/external-tools/tree-tagger-3.2/$PLATFORM/cmd
TREE_TAGGER_LIB=$METAPHOR_DIR/external-tools/tree-tagger-3.2/$PLATFORM/lib
TREE_TAGGER_OPT="-lemma -token -sgml -quiet"

NLTK_TOKENIZER_DIR=$METAPHOR_DIR/external-tools/nltk_tokenizer

MALT_DIR=$METAPHOR_DIR/external-tools/malt-1.5
MALT_RU_DIR=$METAPHOR_DIR/external-tools/malt-ru

TOKENIZER_BIN=$NLTK_TOKENIZER_DIR/nltk_rtokenizer.py

TAGGER_BIN=$TREE_TAGGER_BIN/tree-tagger
TAGGER_PAR=$MALT_RU_DIR/russian.par
LEMMATIZER_BIN=$MALT_RU_DIR/lemmatiser.pl

RU_PIPELINE_DIR=$METAPHOR_DIR/pipelines/Russian

MALT_BIN=$MALT_DIR/malt.jar
MALT_MODEL=rus-test.mco
MALT_IFORMAT=$MALT_RU_DIR/make-malt.pl


CURRENT_DIR=`pwd`
cd $MALT_RU_DIR

if [ -d "$2" ]; then
    python $TOKENIZER_BIN --sentid 1 --normquotes 1 --wptokenizer 0 < "${1:-/dev/stdin}" |
    tee $2/tokenizer_o.txt |
    $TAGGER_BIN $TREE_TAGGER_OPT $TAGGER_PAR |
    tee $2/tagger_o.txt |
    $LEMMATIZER_BIN -l $MALT_RU_DIR/msd-ru-lemma.lex.gz -p $MALT_RU_DIR/wform2011.ptn1 -c $MALT_RU_DIR/cstlemma |
    tee $2/lemmatizer_o.txt |
    $MALT_IFORMAT > /dev/stdout
else
    python $TOKENIZER_BIN --sentid 1 --normquotes 1 --wptokenizer 0 < "${1:-/dev/stdin}" |
    $TAGGER_BIN $TREE_TAGGER_OPT $TAGGER_PAR |
    $LEMMATIZER_BIN -l $MALT_RU_DIR/msd-ru-lemma.lex.gz -p $MALT_RU_DIR/wform2011.ptn1 -c $MALT_RU_DIR/cstlemma |
    $MALT_IFORMAT > "${2:-/dev/stdout}"
fi

cd $CURRENT_DIR
